name: GitHub CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: General checks, tests and build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4

    - name: Use Node.js LTS 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Perform checks and tests
      run: npm test

    - name: Perform self-contained build
      run: npm run build
